FROM ubuntu:20.04

RUN sed -i 's/\(archive\|security\).ubuntu.com/free.nchc.org.tw/' /etc/apt/sources.list
RUN apt update

RUN apt install -y \
    build-essential git wget \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libbz2-dev \
    zlib1g-dev

# RUN sed -i 's/ash/bash/' /etc/passwd
RUN git clone https://github.com/pyenv/pyenv.git ~/.pyenv
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
RUN echo 'export PATH="$PYENV_ROOT/bin:$PYENV_ROOT/shims:$PATH"' >> ~/.bashrc

# CMD [ "/bin/bash" ]
